baseurl = 'https://h3x0c4t.github.io/'
languagecode = 'ru-RU'
paginate = 5
title = 'H3X0C4T'
description = 'Очередной сайт с заметками по информационной безопасности и другим темам.'
theme = 'hugo-theme-stack'

enableRobotsTXT = true

DefaultContentLanguage = "ru"

hasCJKLanguage = false

googleAnalytics = "G-YZ9S2Y2H62"